version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Build started on `date`"
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build   # Change to 'dist' if using Vue or Angular

cache:
  paths:
    - node_modules/**/*   # Optional, speeds up future builds
